### ISSUE TITLE
More automatic way to generate certificates

### ISSUE THREAD

**Issue by zadigus** [ChristianLempa/videos#1]
Hi,

First, I want to thank you a lot for the explanations you provided in your multiple videos / cheatsheets about SSL. It drastically augmented my understanding about self-signed certificates, and for that I am very grateful to you. 

Now, I would like to share with you another way to generate self-signed certificates on kubernetes with cert-manager that does not involve to write any openssl command. I find that way pretty cool and simple. Maybe you want to make a video about it sometime? It is very close to what you showed in your video:

1. you define the root cluster issuer (sorry my vocabulary on the topic might not be very precise, I'm still learning) like this 
```yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: root-issuer
spec:
  selfSigned: {}
```
2.  you define the root CA like this
```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: root-ca
spec:
  isCA: true
  commonName: root-ca
  secretName: root-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: root-issuer
    kind: ClusterIssuer
    group: cert-manager.io
```
3. you define the CA issuer as follows
```yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-issuer
spec:
  ca:
    secretName: root-secret
```
4. you finally define your tls certificate like so
```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-certificate
spec:
  secretName: tls-secret
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  dnsNames:
    - "my-dns-name"
```

With that in place, I was able to achieve the very same result as you did in your video, without using openssl, but instead by using cert-manager's full power. The whole thing is documented [here](https://cert-manager.io/docs/configuration/selfsigned/#bootstrapping-ca-issuers) and [here](https://cert-manager.io/docs/configuration/ca/#deployment).
