### ISSUE TITLE
NGINX Reverse Proxy Config for Teleport Docker container

### ISSUE THREAD

**Issue by mighty-services** [ChristianLempa/videos#23]
Dear Christian,

thanks a lot for your tutorials in this toppic! Great to see others be enthusiastic about teleport :)

I also have a homelab running on proxmox and Nginx reverse Proxy and have several Services running on it, so I simply cant use port 443 by default like you described. I´d like to pass it through the Reverse proxy butcant get it to work. I always get the error

`WARN [MX:PROXY:] "\nERROR REPORT:\nOriginal Error: *trace.BadParameterError multiplexer failed to detect connection protocol`

Based on [this post](https://github.com/gravitational/teleport/discussions/15293?sort=top), I´ve edited the teleport.yml file to this:

```yaml
#version: v2
teleport:
  nodename: teleport
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
#  proxy_listener_mode: multiplex
  cluster_name: teleport.example.com
ssh_service:
  enabled: "yes"
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:443
  public_addr: teleport.example.com:443
  https_keypairs: []
#  acme:
#    enabled: yes
#    email: <Email>
````

In the reverse Proxy I forwarded "teleport.example.com" as https Protokoll to my host-IP on port 443

Can you explain how to configure the Reverse proxy or how to use teleport on another port?
